name: CI

on: [push]

env:
  GPR_URL: "docker.pkg.github.com"
  GPR_USER: "rodeoclash"
  IMAGE_PATH_LATEST_APP: "docker.pkg.github.com/rodeoclash/mere/app:latest"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GPR
        run: docker login ${GPR_URL} -u ${GPR_USER} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Pull the app image from GPR
        run: docker pull ${IMAGE_PATH_LATEST_APP}

      - name: Build the app Docker image
        run: docker build --file app/Dockerfile.dev --tag ${IMAGE_PATH_LATEST_APP} --cache-from ${IMAGE_PATH_LATEST_APP} ./app

      - name: Publish the app image to GPR
        run: docker push ${IMAGE_PATH_LATEST_APP}

  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GPR
        run: docker login ${GPR_URL} -u ${GPR_USER} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: docker-compose -f docker-compose.ci.yml run app mix test --max-cases 1

      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          retention-days: 1
          path: ./screenshots/

  lint:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GPR
        run: docker login ${GPR_URL} -u ${GPR_USER} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Lint prettier
        run: npx prettier@2.4.1 --check "**/*.{js,json,css,md,html,jsx,yml,yaml}"

      - name: Lint elixir
        run: docker-compose -f docker-compose.ci.yml run app mix format --check-formatted
